version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: dubai-donation-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: donation_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: donation-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/donation_db
    depends_on:
      - postgres

  frontend:
    build: ./cms
    container_name: cms-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
